FROM alpine:3.12

RUN apk update && apk add curl supervisor influxdb libc6-compat \
	&& rm -rf /var/cache/apk/*

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.17.0_linux_amd64.tar.gz \
	&& tar -xf telegraf-1.17.0_linux_amd64.tar.gz --strip-components=2 -C / \
	&& rm telegraf-1.17.0_linux_amd64.tar.gz
COPY srcs/telegraf.conf /etc/telegraf/

COPY srcs/supervisord.conf /etc/
COPY srcs/start.sh /

EXPOSE 8086

ENTRYPOINT  sh start.sh
