apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app  : grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      project: grafana
  template:
    metadata:
      labels:
        project: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
  labels:
      app  : grafana
spec:
  type: LoadBalancer
  selector:
    project: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000